//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjAulaWebMVC.ServiceWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceWCF.IServico")]
    public interface IServico {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/Inserir", ReplyAction="http://tempuri.org/IServico/InserirResponse")]
        bool Inserir(Entidade.EquipamentoVO equipamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/Inserir", ReplyAction="http://tempuri.org/IServico/InserirResponse")]
        System.Threading.Tasks.Task<bool> InserirAsync(Entidade.EquipamentoVO equipamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/Selecionar", ReplyAction="http://tempuri.org/IServico/SelecionarResponse")]
        Entidade.EquipamentoVO[] Selecionar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/Selecionar", ReplyAction="http://tempuri.org/IServico/SelecionarResponse")]
        System.Threading.Tasks.Task<Entidade.EquipamentoVO[]> SelecionarAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicoChannel : ProjAulaWebMVC.ServiceWCF.IServico, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicoClient : System.ServiceModel.ClientBase<ProjAulaWebMVC.ServiceWCF.IServico>, ProjAulaWebMVC.ServiceWCF.IServico {
        
        public ServicoClient() {
        }
        
        public ServicoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Inserir(Entidade.EquipamentoVO equipamento) {
            return base.Channel.Inserir(equipamento);
        }
        
        public System.Threading.Tasks.Task<bool> InserirAsync(Entidade.EquipamentoVO equipamento) {
            return base.Channel.InserirAsync(equipamento);
        }
        
        public Entidade.EquipamentoVO[] Selecionar() {
            return base.Channel.Selecionar();
        }
        
        public System.Threading.Tasks.Task<Entidade.EquipamentoVO[]> SelecionarAsync() {
            return base.Channel.SelecionarAsync();
        }
    }
}
